# Generated by Django 5.1.4 on 2024-12-24 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('program_date', models.DateTimeField()),
                ('program_end_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('banner', models.ImageField(upload_to='program_banners/')),
                ('max_participants', models.PositiveIntegerField()),
                ('registrations_count', models.PositiveIntegerField(default=0)),
                ('max_received', models.PositiveIntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipansInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('institute', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='ams.programinfo')),
            ],
        ),
    ]
