# Generated by Django 5.1.4 on 2024-12-24 15:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programinfo',
            name='program_end_date',
        ),
        migrations.AddField(
            model_name='programinfo',
            name='program_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programinfo',
            name='program_date',
            field=models.DateField(),
        ),
    ]
