# Generated by Django 5.1.4 on 2024-12-24 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0002_remove_programinfo_program_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programinfo',
            old_name='program_time',
            new_name='program_datetime',
        ),
        migrations.RemoveField(
            model_name='programinfo',
            name='program_date',
        ),
    ]
