# Generated by Django 5.1.4 on 2024-12-24 15:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0003_rename_program_time_programinfo_program_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programinfo',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='programinfo',
            name='program_datetime',
            field=models.CharField(max_length=30),
        ),
    ]
