# Generated by Django 5.1.4 on 2024-12-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0004_siteinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='site_instagram',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='site_pinterest',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='site_x',
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='site_facebook',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='site_name',
            field=models.CharField(max_length=50),
        ),
    ]
