# Generated by Django 5.1.4 on 2024-12-25 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0007_facebookpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programinfo',
            name='max_participants',
        ),
    ]
